import { useMemo, useState, type ReactNode } from 'react'
import { BarChart3, CalendarDays, ChevronDown, Clock3, LayoutDashboard, Search, Settings, ShoppingBag, Store, Tag, Upload } from 'lucide-react'
type Status='ATIVA'|'BREVE'|'ENCERRADA'
type Promotion={code:string;name:string;oldPrice:string;price:string;store:string;start:string;end:string;detail:string;status:Status}
const promotions:Promotion[]=[
{code:'789456',name:'Coca-Cola 2L',oldPrice:'R$ 12,99',price:'R$ 8,99',store:'Loja Centro',start:'20/09/2026',end:'30/09/2026',detail:'10 dias restantes',status:'ATIVA'},
{code:'123789',name:'Arroz Tipo 1 5kg',oldPrice:'R$ 29,90',price:'R$ 24,90',store:'Loja Norte',start:'25/09/2026',end:'05/10/2026',detail:'3 dias para iniciar',status:'BREVE'},
{code:'456321',name:'Café Torrado 500g',oldPrice:'R$ 18,90',price:'R$ 14,99',store:'Loja Sul',start:'18/09/2026',end:'28/09/2026',detail:'6 dias restantes',status:'ATIVA'},
{code:'987654',name:'Detergente 500ml',oldPrice:'R$ 3,49',price:'R$ 2,49',store:'Loja Centro',start:'01/09/2026',end:'20/09/2026',detail:'Encerrada',status:'ENCERRADA'}]
function App(){const[q,setQ]=useState(''),[store,setStore]=useState(''),[status,setStatus]=useState('')
const filtered=useMemo(()=>promotions.filter(p=>(!q||`${p.code} ${p.name}`.toLowerCase().includes(q.toLowerCase()))&&(!store||p.store===store)&&(!status||p.status===status)),[q,store,status])
return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">AO</div><div>Acompanhamento <span>de Ofertas</span></div></div><nav><a className="active"><LayoutDashboard/>Visão geral</a><a><Tag/>Promoções</a><a><Store/>Lojas</a><a><CalendarDays/>Vigências</a><a><Upload/>Importar planilha</a><a><Settings/>Configurações</a></nav><div className="sidebar-footer">Protótipo visual<br/><strong>v0.1.0</strong></div></aside><main><header><div><h1>Visão geral</h1><p>Acompanhe suas promoções de forma simples e visual.</p></div><button className="primary"><Upload size={17}/>Importar planilha</button></header><section className="stats"><Stat icon={<Tag/>} value="128" label="Promoções ativas"/><Stat icon={<ShoppingBag/>} value="86" label="Produtos em oferta"/><Stat icon={<Store/>} value="14" label="Lojas participantes"/><Stat icon={<Clock3/>} value="12" label="Vencendo em breve"/></section><section className="panel"><div className="panel-head"><div><h2>Promoções</h2><span>{filtered.length} registros exibidos</span></div><button className="ghost"><BarChart3 size={16}/>Visão analítica</button></div><div className="filters"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por código ou produto..."/></div><Select value={store} setValue={setStore} options={['Loja Centro','Loja Norte','Loja Sul']} placeholder="Todas as lojas"/><Select value={status} setValue={setStatus} options={['ATIVA','BREVE','ENCERRADA']} placeholder="Todos os status"/></div><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Preço promocional</th><th>Loja</th><th>Vigência</th><th>Status</th></tr></thead><tbody>{filtered.map(p=><tr key={p.code}><td><b>{p.name}</b><small>Código: {p.code}</small></td><td><del>{p.oldPrice}</del><strong>{p.price}</strong></td><td><span className="store"><Store size={15}/>{p.store}</span></td><td>{p.start} → {p.end}<small>{p.detail}</small></td><td><Badge status={p.status}/></td></tr>)}{!filtered.length&&<tr><td colSpan={5} className="empty">Nenhuma promoção encontrada.</td></tr>}</tbody></table></div></section></main></div>}
function Stat({icon,value,label}:{icon:ReactNode;value:string;label:string}){return <div className="stat"><div className="stat-icon">{icon}</div><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>}
function Select({value,setValue,options,placeholder}:{value:string;setValue:(v:string)=>void;options:string[];placeholder:string}){return <label className="select"><select value={value} onChange={e=>setValue(e.target.value)}><option value="">{placeholder}</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={16}/></label>}
function Badge({status}:{status:Status}){return <span className={`badge ${status.toLowerCase()}`}>● {status==='ATIVA'?'ATIVA':status==='BREVE'?'BREVE':'ENCERRADA'}</span>}
export default App
